- id: vx-check-deactivate
  name: Check deactivate.jinja syntax
  description: Check if the file deactivate.jinja is correctly formatted
  entry: check_deactivate
  args: []
  language: python
  types_or: [json]
